name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # サブモジュールを含める

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/rrst-nhk-project/rrst-ros2-ws:latest
            ghcr.io/rrst-nhk-project/rrst-ros2-ws:${{ github.sha }}
