name: ROS 2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy  # 適切なROS 2ディストリビューションを指定

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions

      - name: Create ROS 2 workspace
        run: |
          mkdir -p ros2_ws/src
          mv $(ls -d */ | grep -v 'ros2_ws') ros2_ws/src/ || true  # 他のディレクトリをsrcに移動
          cd ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          cd ros2_ws
          colcon build --symlink-install

      - name: Run tests
        run: |
          cd ros2_ws
          colcon test
          colcon test-result --verbose
